export const SCREENS = {
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  RESET_PASSWORD: 'ResetPassword',
  TAB_NAVIGATION: 'TabNavigation',
  PROFILE_SETUP: 'ProfileSetup',
  MY_PROFILE: 'MyProfile',
  REPORTS: 'Reports',
  FAVORITE: 'Favorite',
  LOCATIONS: 'Locations',
  ADD_REPORT: 'AddReport',
  EDIT_PROFILE: 'EditProfile',
  USER_DOCUMENTS: 'Documents',
  FILTER: 'Filter',
  REPORT_CONTENT: 'ReportContent',
  CHAT: 'Chat',
  TYPE_REPORTS: 'TypeReports',
};
